import type { Metadata } from "next";
import NavBar from "@/components/nav-bar";

// Metadata for the page (SEO and other settings)
export const metadata: Metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Page description
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* You can include additional meta tags, favicon, etc. here */}
      </head>
      <body>
        <NavBar />
        <main>{children}</main> {/* Wrapping children in <main> for better structure */}
      </body>
    </html>
  );
}
