import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "@/context/auth-context";
import UserDetailsContextProvider from "@/context/userDetails-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <UserDetailsContextProvider>
            {children}
          </UserDetailsContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
